// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: account_service.proto

package grpcApi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	UserData      map[string]*structpb.Value `protobuf:"bytes,1,rep,name=userData,proto3" json:"userData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_account_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetUserData() map[string]*structpb.Value {
	if x != nil {
		return x.UserData
	}
	return nil
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_account_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetAccountByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByEmailRequest) Reset() {
	*x = GetAccountByEmailRequest{}
	mi := &file_account_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByEmailRequest) ProtoMessage() {}

func (x *GetAccountByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByEmailRequest) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetAccountResponse_Account_
	//	*GetAccountResponse_Error
	Result        isGetAccountResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_account_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountResponse) GetResult() isGetAccountResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetAccountResponse) GetAccount() *GetAccountResponse_Account {
	if x != nil {
		if x, ok := x.Result.(*GetAccountResponse_Account_); ok {
			return x.Account
		}
	}
	return nil
}

func (x *GetAccountResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*GetAccountResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetAccountResponse_Result interface {
	isGetAccountResponse_Result()
}

type GetAccountResponse_Account_ struct {
	Account *GetAccountResponse_Account `protobuf:"bytes,1,opt,name=account,proto3,oneof"`
}

type GetAccountResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetAccountResponse_Account_) isGetAccountResponse_Result() {}

func (*GetAccountResponse_Error) isGetAccountResponse_Result() {}

type GetAccessTokenPayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessTokenPayloadRequest) Reset() {
	*x = GetAccessTokenPayloadRequest{}
	mi := &file_account_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessTokenPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenPayloadRequest) ProtoMessage() {}

func (x *GetAccessTokenPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenPayloadRequest.ProtoReflect.Descriptor instead.
func (*GetAccessTokenPayloadRequest) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccessTokenPayloadRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccessTokenPayloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetAccessTokenPayloadResponse_Claims
	//	*GetAccessTokenPayloadResponse_Error
	Result        isGetAccessTokenPayloadResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessTokenPayloadResponse) Reset() {
	*x = GetAccessTokenPayloadResponse{}
	mi := &file_account_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessTokenPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenPayloadResponse) ProtoMessage() {}

func (x *GetAccessTokenPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenPayloadResponse.ProtoReflect.Descriptor instead.
func (*GetAccessTokenPayloadResponse) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccessTokenPayloadResponse) GetResult() isGetAccessTokenPayloadResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetAccessTokenPayloadResponse) GetClaims() *AccessTokenClaims {
	if x != nil {
		if x, ok := x.Result.(*GetAccessTokenPayloadResponse_Claims); ok {
			return x.Claims
		}
	}
	return nil
}

func (x *GetAccessTokenPayloadResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*GetAccessTokenPayloadResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetAccessTokenPayloadResponse_Result interface {
	isGetAccessTokenPayloadResponse_Result()
}

type GetAccessTokenPayloadResponse_Claims struct {
	Claims *AccessTokenClaims `protobuf:"bytes,1,opt,name=claims,proto3,oneof"`
}

type GetAccessTokenPayloadResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetAccessTokenPayloadResponse_Claims) isGetAccessTokenPayloadResponse_Result() {}

func (*GetAccessTokenPayloadResponse_Error) isGetAccessTokenPayloadResponse_Result() {}

type AccessTokenClaims struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Values        map[string]*structpb.Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTokenClaims) Reset() {
	*x = AccessTokenClaims{}
	mi := &file_account_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTokenClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenClaims) ProtoMessage() {}

func (x *AccessTokenClaims) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenClaims.ProtoReflect.Descriptor instead.
func (*AccessTokenClaims) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{6}
}

func (x *AccessTokenClaims) GetValues() map[string]*structpb.Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type ValidateAccountRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	UserData      map[string]*structpb.Value `protobuf:"bytes,1,rep,name=userData,proto3" json:"userData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccountRequest) Reset() {
	*x = ValidateAccountRequest{}
	mi := &file_account_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccountRequest) ProtoMessage() {}

func (x *ValidateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccountRequest.ProtoReflect.Descriptor instead.
func (*ValidateAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateAccountRequest) GetUserData() map[string]*structpb.Value {
	if x != nil {
		return x.UserData
	}
	return nil
}

type ValidateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccountResponse) Reset() {
	*x = ValidateAccountResponse{}
	mi := &file_account_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccountResponse) ProtoMessage() {}

func (x *ValidateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccountResponse.ProtoReflect.Descriptor instead.
func (*ValidateAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateAccountResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetAccountResponse_Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse_Account) Reset() {
	*x = GetAccountResponse_Account{}
	mi := &file_account_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse_Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse_Account) ProtoMessage() {}

func (x *GetAccountResponse_Account) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse_Account.ProtoReflect.Descriptor instead.
func (*GetAccountResponse_Account) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetAccountResponse_Account) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAccountResponse_Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_account_service_proto protoreflect.FileDescriptor

const file_account_service_proto_rawDesc = "" +
	"\n" +
	"\x15account_service.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\verror.proto\"\xac\x01\n" +
	"\x14CreateAccountRequest\x12?\n" +
	"\buserData\x18\x01 \x03(\v2#.CreateAccountRequest.UserDataEntryR\buserData\x1aS\n" +
	"\rUserDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"D\n" +
	"\x15CreateAccountResponse\x12!\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"0\n" +
	"\x18GetAccountByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\xb6\x01\n" +
	"\x12GetAccountResponse\x127\n" +
	"\aaccount\x18\x01 \x01(\v2\x1b.GetAccountResponse.AccountH\x00R\aaccount\x12\x1e\n" +
	"\x05error\x18\x02 \x01(\v2\x06.ErrorH\x00R\x05error\x1a=\n" +
	"\aAccount\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05emailB\b\n" +
	"\x06result\"<\n" +
	"\x1cGetAccessTokenPayloadRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\tR\taccountId\"w\n" +
	"\x1dGetAccessTokenPayloadResponse\x12,\n" +
	"\x06claims\x18\x01 \x01(\v2\x12.AccessTokenClaimsH\x00R\x06claims\x12\x1e\n" +
	"\x05error\x18\x02 \x01(\v2\x06.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x9e\x01\n" +
	"\x11AccessTokenClaims\x126\n" +
	"\x06values\x18\x01 \x03(\v2\x1e.AccessTokenClaims.ValuesEntryR\x06values\x1aQ\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xb0\x01\n" +
	"\x16ValidateAccountRequest\x12A\n" +
	"\buserData\x18\x01 \x03(\v2%.ValidateAccountRequest.UserDataEntryR\buserData\x1aS\n" +
	"\rUserDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"F\n" +
	"\x17ValidateAccountResponse\x12!\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\xbf\x02\n" +
	"\x0eAccountService\x12@\n" +
	"\rCreateAccount\x12\x15.CreateAccountRequest\x1a\x16.CreateAccountResponse\"\x00\x12E\n" +
	"\x11GetAccountByEmail\x12\x19.GetAccountByEmailRequest\x1a\x13.GetAccountResponse\"\x00\x12X\n" +
	"\x15GetAccessTokenPayload\x12\x1d.GetAccessTokenPayloadRequest\x1a\x1e.GetAccessTokenPayloadResponse\"\x00\x12J\n" +
	"\x13ValidateAccountData\x12\x17.ValidateAccountRequest\x1a\x18.ValidateAccountResponse\"\x00B4Z2github.com/PavelShe11/studbridge/authMicro/grpcApib\x06proto3"

var (
	file_account_service_proto_rawDescOnce sync.Once
	file_account_service_proto_rawDescData []byte
)

func file_account_service_proto_rawDescGZIP() []byte {
	file_account_service_proto_rawDescOnce.Do(func() {
		file_account_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_service_proto_rawDesc), len(file_account_service_proto_rawDesc)))
	})
	return file_account_service_proto_rawDescData
}

var file_account_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_account_service_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),          // 0: CreateAccountRequest
	(*CreateAccountResponse)(nil),         // 1: CreateAccountResponse
	(*GetAccountByEmailRequest)(nil),      // 2: GetAccountByEmailRequest
	(*GetAccountResponse)(nil),            // 3: GetAccountResponse
	(*GetAccessTokenPayloadRequest)(nil),  // 4: GetAccessTokenPayloadRequest
	(*GetAccessTokenPayloadResponse)(nil), // 5: GetAccessTokenPayloadResponse
	(*AccessTokenClaims)(nil),             // 6: AccessTokenClaims
	(*ValidateAccountRequest)(nil),        // 7: ValidateAccountRequest
	(*ValidateAccountResponse)(nil),       // 8: ValidateAccountResponse
	nil,                                   // 9: CreateAccountRequest.UserDataEntry
	(*GetAccountResponse_Account)(nil),    // 10: GetAccountResponse.Account
	nil,                                   // 11: AccessTokenClaims.ValuesEntry
	nil,                                   // 12: ValidateAccountRequest.UserDataEntry
	(*Error)(nil),                         // 13: Error
	(*structpb.Value)(nil),                // 14: google.protobuf.Value
}
var file_account_service_proto_depIdxs = []int32{
	9,  // 0: CreateAccountRequest.userData:type_name -> CreateAccountRequest.UserDataEntry
	13, // 1: CreateAccountResponse.error:type_name -> Error
	10, // 2: GetAccountResponse.account:type_name -> GetAccountResponse.Account
	13, // 3: GetAccountResponse.error:type_name -> Error
	6,  // 4: GetAccessTokenPayloadResponse.claims:type_name -> AccessTokenClaims
	13, // 5: GetAccessTokenPayloadResponse.error:type_name -> Error
	11, // 6: AccessTokenClaims.values:type_name -> AccessTokenClaims.ValuesEntry
	12, // 7: ValidateAccountRequest.userData:type_name -> ValidateAccountRequest.UserDataEntry
	13, // 8: ValidateAccountResponse.error:type_name -> Error
	14, // 9: CreateAccountRequest.UserDataEntry.value:type_name -> google.protobuf.Value
	14, // 10: AccessTokenClaims.ValuesEntry.value:type_name -> google.protobuf.Value
	14, // 11: ValidateAccountRequest.UserDataEntry.value:type_name -> google.protobuf.Value
	0,  // 12: AccountService.CreateAccount:input_type -> CreateAccountRequest
	2,  // 13: AccountService.GetAccountByEmail:input_type -> GetAccountByEmailRequest
	4,  // 14: AccountService.GetAccessTokenPayload:input_type -> GetAccessTokenPayloadRequest
	7,  // 15: AccountService.ValidateAccountData:input_type -> ValidateAccountRequest
	1,  // 16: AccountService.CreateAccount:output_type -> CreateAccountResponse
	3,  // 17: AccountService.GetAccountByEmail:output_type -> GetAccountResponse
	5,  // 18: AccountService.GetAccessTokenPayload:output_type -> GetAccessTokenPayloadResponse
	8,  // 19: AccountService.ValidateAccountData:output_type -> ValidateAccountResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_account_service_proto_init() }
func file_account_service_proto_init() {
	if File_account_service_proto != nil {
		return
	}
	file_error_proto_init()
	file_account_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_account_service_proto_msgTypes[3].OneofWrappers = []any{
		(*GetAccountResponse_Account_)(nil),
		(*GetAccountResponse_Error)(nil),
	}
	file_account_service_proto_msgTypes[5].OneofWrappers = []any{
		(*GetAccessTokenPayloadResponse_Claims)(nil),
		(*GetAccessTokenPayloadResponse_Error)(nil),
	}
	file_account_service_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_service_proto_rawDesc), len(file_account_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_service_proto_goTypes,
		DependencyIndexes: file_account_service_proto_depIdxs,
		MessageInfos:      file_account_service_proto_msgTypes,
	}.Build()
	File_account_service_proto = out.File
	file_account_service_proto_goTypes = nil
	file_account_service_proto_depIdxs = nil
}
