// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Pavel Sheludyakov",
            "url": "https://github.com/PavelShe11/studBridge"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login/confirmEmail": {
            "post": {
                "description": "Проверяет OTP-код и возвращает пару JWT токенов (access + refresh).\nОбязательные поля: email (string), code (string).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "Подтвердить вход",
                "parameters": [
                    {
                        "description": "Email и OTP-код",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PavelShe11_studbridge_authMicro_internal_infrastructure_inbound_rest_models.TokensResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entity.BaseValidationError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entity.BaseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entity.BaseError"
                        }
                    }
                }
            }
        },
        "/login/sendCodeEmail": {
            "post": {
                "description": "Находит аккаунт по email и генерирует OTP-код для входа.\nОбязательное поле: email (string).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "Отправить код входа",
                "parameters": [
                    {
                        "description": "Email пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PavelShe11_studbridge_authMicro_internal_infrastructure_inbound_rest_models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entity.BaseValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entity.BaseError"
                        }
                    }
                }
            }
        },
        "/refreshToken": {
            "post": {
                "description": "Проверяет refresh токен и возвращает новую пару JWT токенов (access + refresh). Старый refresh токен инвалидируется.\nОбязательное поле: refreshToken (string).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Обновить токены",
                "parameters": [
                    {
                        "description": "Refresh токен",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PavelShe11_studbridge_authMicro_internal_infrastructure_inbound_rest_models.TokensResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entity.BaseError"
                        }
                    },
                    "401": {
                        "description": "Токен недействителен или истёк"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entity.BaseError"
                        }
                    }
                }
            }
        },
        "/registration": {
            "post": {
                "description": "Создаёт или продлевает сессию регистрации и генерирует OTP-код.\nНабор полей в теле запроса определяется правилами валидации user-service (ValidateAccountData).\nAuth service передаёт данные напрямую — без фиксированной схемы.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "registration"
                ],
                "summary": "Отправить код регистрации",
                "parameters": [
                    {
                        "description": "Данные пользователя (схема определяется user-service)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PavelShe11_studbridge_authMicro_internal_infrastructure_inbound_rest_models.RegistrationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entity.BaseValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entity.BaseError"
                        }
                    }
                }
            }
        },
        "/registration/confirmEmail": {
            "post": {
                "description": "Проверяет OTP-код из сессии регистрации, затем передаёт данные в user-service для создания аккаунта.\nНабор полей определяется user-service. Обязательные поля: email (string), code (string).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "registration"
                ],
                "summary": "Подтвердить email при регистрации",
                "parameters": [
                    {
                        "description": "Email, OTP-код и данные пользователя (схема определяется user-service)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Регистрация успешно завершена"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entity.BaseValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entity.BaseError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.BaseError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "entity.BaseValidationError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "fieldErrors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.FieldError"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "entity.FieldError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "nameField": {
                    "type": "string"
                }
            }
        },
        "github_com_PavelShe11_studbridge_authMicro_internal_infrastructure_inbound_rest_models.LoginResponse": {
            "type": "object",
            "properties": {
                "codeExpires": {
                    "type": "integer"
                },
                "codePattern": {
                    "type": "string"
                }
            }
        },
        "github_com_PavelShe11_studbridge_authMicro_internal_infrastructure_inbound_rest_models.RegistrationResponse": {
            "type": "object",
            "properties": {
                "codeExpires": {
                    "type": "integer"
                },
                "codePattern": {
                    "type": "string"
                }
            }
        },
        "github_com_PavelShe11_studbridge_authMicro_internal_infrastructure_inbound_rest_models.TokensResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "accessTokenExpires": {
                    "type": "integer"
                },
                "refreshToken": {
                    "type": "string"
                },
                "refreshTokenExpires": {
                    "type": "integer"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Двухшаговая регистрация с OTP-кодом",
            "name": "registration"
        },
        {
            "description": "Двухшаговый вход с OTP-кодом",
            "name": "login"
        },
        {
            "description": "Управление JWT токенами",
            "name": "tokens"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/auth/v1",
	Schemes:          []string{},
	Title:            "StudBridge Auth API",
	Description:      "Сервис аутентификации: регистрация, вход по OTP-коду, управление JWT токенами.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
