// Code generated by mockery v2.53.5. DO NOT EDIT.

package port

import (
	context "context"

	entity "github.com/PavelShe11/studbridge/authMicro/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockAccountProvider is an autogenerated mock type for the AccountProvider type
type MockAccountProvider struct {
	mock.Mock
}

type MockAccountProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountProvider) EXPECT() *MockAccountProvider_Expecter {
	return &MockAccountProvider_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function with given fields: ctx, userData, lang
func (_m *MockAccountProvider) CreateAccount(ctx context.Context, userData map[string]interface{}, lang string) error {
	ret := _m.Called(ctx, userData, lang)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}, string) error); ok {
		r0 = rf(ctx, userData, lang)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountProvider_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MockAccountProvider_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userData map[string]interface{}
//   - lang string
func (_e *MockAccountProvider_Expecter) CreateAccount(ctx interface{}, userData interface{}, lang interface{}) *MockAccountProvider_CreateAccount_Call {
	return &MockAccountProvider_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, userData, lang)}
}

func (_c *MockAccountProvider_CreateAccount_Call) Run(run func(ctx context.Context, userData map[string]interface{}, lang string)) *MockAccountProvider_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]interface{}), args[2].(string))
	})
	return _c
}

func (_c *MockAccountProvider_CreateAccount_Call) Return(_a0 error) *MockAccountProvider_CreateAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountProvider_CreateAccount_Call) RunAndReturn(run func(context.Context, map[string]interface{}, string) error) *MockAccountProvider_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessTokenPayload provides a mock function with given fields: ctx, accountId
func (_m *MockAccountProvider) GetAccessTokenPayload(ctx context.Context, accountId string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessTokenPayload")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]interface{}, error)); ok {
		return rf(ctx, accountId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]interface{}); ok {
		r0 = rf(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountProvider_GetAccessTokenPayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessTokenPayload'
type MockAccountProvider_GetAccessTokenPayload_Call struct {
	*mock.Call
}

// GetAccessTokenPayload is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *MockAccountProvider_Expecter) GetAccessTokenPayload(ctx interface{}, accountId interface{}) *MockAccountProvider_GetAccessTokenPayload_Call {
	return &MockAccountProvider_GetAccessTokenPayload_Call{Call: _e.mock.On("GetAccessTokenPayload", ctx, accountId)}
}

func (_c *MockAccountProvider_GetAccessTokenPayload_Call) Run(run func(ctx context.Context, accountId string)) *MockAccountProvider_GetAccessTokenPayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountProvider_GetAccessTokenPayload_Call) Return(_a0 map[string]interface{}, _a1 error) *MockAccountProvider_GetAccessTokenPayload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountProvider_GetAccessTokenPayload_Call) RunAndReturn(run func(context.Context, string) (map[string]interface{}, error)) *MockAccountProvider_GetAccessTokenPayload_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByEmail provides a mock function with given fields: ctx, email
func (_m *MockAccountProvider) GetAccountByEmail(ctx context.Context, email string) (*entity.Account, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByEmail")
	}

	var r0 *entity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Account, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Account); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountProvider_GetAccountByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByEmail'
type MockAccountProvider_GetAccountByEmail_Call struct {
	*mock.Call
}

// GetAccountByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAccountProvider_Expecter) GetAccountByEmail(ctx interface{}, email interface{}) *MockAccountProvider_GetAccountByEmail_Call {
	return &MockAccountProvider_GetAccountByEmail_Call{Call: _e.mock.On("GetAccountByEmail", ctx, email)}
}

func (_c *MockAccountProvider_GetAccountByEmail_Call) Run(run func(ctx context.Context, email string)) *MockAccountProvider_GetAccountByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountProvider_GetAccountByEmail_Call) Return(_a0 *entity.Account, _a1 error) *MockAccountProvider_GetAccountByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountProvider_GetAccountByEmail_Call) RunAndReturn(run func(context.Context, string) (*entity.Account, error)) *MockAccountProvider_GetAccountByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccountData provides a mock function with given fields: ctx, userData, lang
func (_m *MockAccountProvider) ValidateAccountData(ctx context.Context, userData map[string]interface{}, lang string) error {
	ret := _m.Called(ctx, userData, lang)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccountData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}, string) error); ok {
		r0 = rf(ctx, userData, lang)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountProvider_ValidateAccountData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccountData'
type MockAccountProvider_ValidateAccountData_Call struct {
	*mock.Call
}

// ValidateAccountData is a helper method to define mock.On call
//   - ctx context.Context
//   - userData map[string]interface{}
//   - lang string
func (_e *MockAccountProvider_Expecter) ValidateAccountData(ctx interface{}, userData interface{}, lang interface{}) *MockAccountProvider_ValidateAccountData_Call {
	return &MockAccountProvider_ValidateAccountData_Call{Call: _e.mock.On("ValidateAccountData", ctx, userData, lang)}
}

func (_c *MockAccountProvider_ValidateAccountData_Call) Run(run func(ctx context.Context, userData map[string]interface{}, lang string)) *MockAccountProvider_ValidateAccountData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]interface{}), args[2].(string))
	})
	return _c
}

func (_c *MockAccountProvider_ValidateAccountData_Call) Return(_a0 error) *MockAccountProvider_ValidateAccountData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountProvider_ValidateAccountData_Call) RunAndReturn(run func(context.Context, map[string]interface{}, string) error) *MockAccountProvider_ValidateAccountData_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountProvider creates a new instance of MockAccountProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountProvider {
	mock := &MockAccountProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
