// Code generated by mockery v2.53.5. DO NOT EDIT.

package port

import (
	context "context"

	entity "github.com/PavelShe11/studbridge/authMicro/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockRegistrationSessionRepository is an autogenerated mock type for the RegistrationSessionRepository type
type MockRegistrationSessionRepository struct {
	mock.Mock
}

type MockRegistrationSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistrationSessionRepository) EXPECT() *MockRegistrationSessionRepository_Expecter {
	return &MockRegistrationSessionRepository_Expecter{mock: &_m.Mock}
}

// CleanExpired provides a mock function with given fields: ctx
func (_m *MockRegistrationSessionRepository) CleanExpired(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegistrationSessionRepository_CleanExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanExpired'
type MockRegistrationSessionRepository_CleanExpired_Call struct {
	*mock.Call
}

// CleanExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRegistrationSessionRepository_Expecter) CleanExpired(ctx interface{}) *MockRegistrationSessionRepository_CleanExpired_Call {
	return &MockRegistrationSessionRepository_CleanExpired_Call{Call: _e.mock.On("CleanExpired", ctx)}
}

func (_c *MockRegistrationSessionRepository_CleanExpired_Call) Run(run func(ctx context.Context)) *MockRegistrationSessionRepository_CleanExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRegistrationSessionRepository_CleanExpired_Call) Return(_a0 error) *MockRegistrationSessionRepository_CleanExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistrationSessionRepository_CleanExpired_Call) RunAndReturn(run func(context.Context) error) *MockRegistrationSessionRepository_CleanExpired_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByEmail provides a mock function with given fields: ctx, email
func (_m *MockRegistrationSessionRepository) DeleteByEmail(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegistrationSessionRepository_DeleteByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByEmail'
type MockRegistrationSessionRepository_DeleteByEmail_Call struct {
	*mock.Call
}

// DeleteByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRegistrationSessionRepository_Expecter) DeleteByEmail(ctx interface{}, email interface{}) *MockRegistrationSessionRepository_DeleteByEmail_Call {
	return &MockRegistrationSessionRepository_DeleteByEmail_Call{Call: _e.mock.On("DeleteByEmail", ctx, email)}
}

func (_c *MockRegistrationSessionRepository_DeleteByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRegistrationSessionRepository_DeleteByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRegistrationSessionRepository_DeleteByEmail_Call) Return(_a0 error) *MockRegistrationSessionRepository_DeleteByEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistrationSessionRepository_DeleteByEmail_Call) RunAndReturn(run func(context.Context, string) error) *MockRegistrationSessionRepository_DeleteByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *MockRegistrationSessionRepository) FindByEmail(ctx context.Context, email string) (*entity.RegistrationSession, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entity.RegistrationSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.RegistrationSession, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.RegistrationSession); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RegistrationSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegistrationSessionRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockRegistrationSessionRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRegistrationSessionRepository_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockRegistrationSessionRepository_FindByEmail_Call {
	return &MockRegistrationSessionRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockRegistrationSessionRepository_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRegistrationSessionRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRegistrationSessionRepository_FindByEmail_Call) Return(_a0 *entity.RegistrationSession, _a1 error) *MockRegistrationSessionRepository_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegistrationSessionRepository_FindByEmail_Call) RunAndReturn(run func(context.Context, string) (*entity.RegistrationSession, error)) *MockRegistrationSessionRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, session
func (_m *MockRegistrationSessionRepository) Save(ctx context.Context, session *entity.RegistrationSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.RegistrationSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegistrationSessionRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRegistrationSessionRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - session *entity.RegistrationSession
func (_e *MockRegistrationSessionRepository_Expecter) Save(ctx interface{}, session interface{}) *MockRegistrationSessionRepository_Save_Call {
	return &MockRegistrationSessionRepository_Save_Call{Call: _e.mock.On("Save", ctx, session)}
}

func (_c *MockRegistrationSessionRepository_Save_Call) Run(run func(ctx context.Context, session *entity.RegistrationSession)) *MockRegistrationSessionRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.RegistrationSession))
	})
	return _c
}

func (_c *MockRegistrationSessionRepository_Save_Call) Return(_a0 error) *MockRegistrationSessionRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistrationSessionRepository_Save_Call) RunAndReturn(run func(context.Context, *entity.RegistrationSession) error) *MockRegistrationSessionRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegistrationSessionRepository creates a new instance of MockRegistrationSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistrationSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistrationSessionRepository {
	mock := &MockRegistrationSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
